USB_VID = 0x239A
USB_PID = 0x8014
USB_PRODUCT = "PyPen Prototype"
USB_MANUFACTURER = "Oddly Specific Objects"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"
LONGINT_IMPL = MPZ

CIRCUITPY_FRAMEBUFFERIO = 1
CIRCUITPY_SHARPDISPLAY = 1
